### ISSUE TITLE
Create GitHub Actions for releasing tagged versions of `workflows`

### ISSUE THREAD

**Issue by kabilar** [datajoint/datajoint-elements#106]

**Comment by CBroz1** [comment]
Transferred from `workflow-array-ephys`, as it applies to all workflows

**Comment by CBroz1** [comment]
@kabilar Is this addressed by current efforts to standardized `/.github/workflows/development.yml` ?

**Comment by kabilar** [comment]
Thanks @CBroz1.  I would like to set up the same automation around releasing the `workflows` as we have for the `elements` (expect publishing to PyPI).  I have updated the title to reflect this specific feature request.

**Comment by CBroz1** [comment]
On Ice pending some decisions regarding CI/CD for workflows. [See discussion](https://github.com/datajoint/workflow-calcium-imaging/pull/63#issuecomment-1152480611)

**Comment by kabilar** [comment]
Thanks @yambottle!
