### ISSUE TITLE
`ephys.no_curation` documentation

### ISSUE THREAD

**Issue by CBroz1** [datajoint/datajoint-elements#113]
Currently [the ephys description page](https://elements.datajoint.org/description/array_ephys/) 
- is not rendering bullets correctly
- makes no mention of the `no_curation` schema, on which NWB relies. We'll need to be able to direct people somewhere to properly use NWB export. 

Upcoming poster presentation of NWB export puts some pressure on this

**Comment by kabilar** [comment]
Thanks @CBroz1.  Can you please show @sidhulyalkar how to make updates to https://elements.datajoint.org?

**Comment by CBroz1** [comment]
Fixed by #114
