### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by kabilar** [datajoint/datajoint-elements#138]
- [ ] datajoint-elements
- [x] element-lab
- [x] element-animal
- [x] element-session
- [x] element-event
- [ ] element-array-ephys
- [ ] element-calcium-imaging
- [ ] element-miniscope
- [ ] element-deeplabcut
- [ ] element-electrode-localization
- [ ] element-facemap
- [ ] element-visual-stimulus
- [x] element-interface
- [ ] element-optogenetics
- [x] workflow-session
- [x] workflow-array-ephys
- [ ] workflow-calcium-imaging
- [x] workflow-miniscope
- [ ] workflow-deeplabcut
- [ ] workflow-facemap

**Comment by CBroz1** [comment]
@dimitri-yatsenko suggested revising our strategy in favor of linking to a central code of conduct doc

**Comment by dimitri-yatsenko** [comment]
> 

@CBroz1 I just noted how we handle CONTRIBUTING.  I guess the difference is that our contribution guidelines are a living document that may evolve, so keeping one copy is important.

**Comment by kabilar** [comment]
Closing as keeping all of the repos updated is not a priority.
