### ISSUE TITLE
Franke et al, 2022, Nature

### ISSUE THREAD

**Issue by CBroz1** [datajoint/datajoint-elements#147]
## Publications Page Edit

Franke, K., Willeke, K. F., Ponder, K., Galdamez, M., Zhou, N., Muhammad, T., ... & Tolias, A. S. (2022). State-dependent pupil dilation rapidly shifts visual feature selectivity. *Nature*, 1-7.

**Comment by kabilar** [comment]
Addressed in https://github.com/datajoint-company/datajoint-docs/pull/7.
