### ISSUE TITLE
Wang et al, 2022, Nature communications

### ISSUE THREAD

**Issue by CBroz1** [datajoint/datajoint-elements#148]
[Link](https://www.nature.com/articles/s41467-022-33364-z)

Wang, Y., Chiola, S., Yang, G., Russell, C., Armstrong, C. J., Wu, Y., ... & Shcheglovitov, A. (2022). Modeling human telencephalic development and autism-associated SHANK3 deficiency using organoids generated from single neural rosettes. *Nature Communications*, 13(1), 1-25.

**Comment by kabilar** [comment]
Thanks.  Addressed in https://github.com/datajoint-company/datajoint-docs/pull/7.
