### ISSUE TITLE
Create joint sustainability roadmap with Suite2p developers

### ISSUE THREAD

**Issue by kabilar** [datajoint/datajoint-elements#35]
See [here](https://github.com/datajoint/datajoint-elements/blob/main/management/selection.md?plain=1#L25
) for more details.

**Comment by CBroz1** [comment]
@kabilar, would you mind making an email introduction to Carson Stringer? Now that the holidays are behind us, it might be a good time to get the ball rolling there. I can follow-up with a description of our aims and a copy of the Joint Sustainability Roadmap template

**Comment by kabilar** [comment]
Thanks @CBroz1.  Yes, I will send an email this week.
