### ISSUE TITLE
Where to include modality-specific lab-general tables? e.g. Equipment

### ISSUE THREAD

**Issue by CBroz1** [datajoint/datajoint-elements#39]
### Problem
1. Elements are designed to be modality-specific and modular. 
2. Some modality-specific tables are conceptually related to the lab (e.g., calcium imaging equipment).
3. Fully specified NWB export functions should incorporate some of this information, if available.
4. In some cases, `make` functions will depend on equipment variables (e.g., treadmill size for speed calculations)

### Requirements
1. Provide users models of these tables for supporting inclusion in NWB export.
2. Keep tables with conceptually equivalent information (e.g., Lab vs. modality-specific data collection).
3. Tables should be readily-editable to conform to lab or experiment specifics.

### Solutions
1. **Status Quo:** Include models in relevant workflow.
   - Pro: Provides model, can be referenced by NWB function.
   - Con: Forces in-depth code review of workflows instead of 'out-of-the-box' working elements.
   - Next steps: Add documentation to each element about required user-specified tables.
2. **Upstream:** Expand Lab Schema, potentially as part tables (see [drafted example](https://github.com/datajoint/element-lab/pull/11/files#diff-d81eea85d273db9093a9fb34e52146a4a26917f1b8fab9fedc605123da357365R162-R169)).
	 - Pro: Information is where it is expected. 'Out-of-the-box' PyPi installation.
	 - Con: Declares unnecessary tables for many users. Could they be conditionally activated?
	 - Next steps: Continual expansion of `element-lab` for each modality.
3. **Downstream:** Add an `equipment` schema to each element.
	 - Pro: Preserves modality-specificity of each element.
	 - Con: Forces local-installs (not PyPi) for any user-specific fields. This is always the case.
	 - Next steps: Migrate existing workflow-specified tables to respective elements.

### Examples
As we expand the number of modalities we support, the list will grow.
1. Calcium Imaging Scanner
   - [As defined in workflow pipeline](https://github.com/datajoint/workflow-calcium-imaging/blob/main/workflow_calcium_imaging/pipeline.py#L32-L36)
   - [As a potential table in the `lab` schema](https://github.com/datajoint/element-lab/pull/11/files#diff-d81eea85d273db9093a9fb34e52146a4a26917f1b8fab9fedc605123da357365R162-R169)
2. Ephys skull reference point - [As defined in workflow pipeline](https://github.com/datajoint/workflow-array-ephys/blob/main/workflow_array_ephys/pipeline.py#L31-L35)
3. Future: `element-behavior` arena, camera, and treadmill information.

**Comment by CBroz1** [comment]
Soliciting input from @iamamutt , @ttngu207 , and @kabilar .

**Comment by kabilar** [comment]
Thanks for the thorough explanation, @CBroz1.  After thinking about this a bit more, I am leaning towards option 1 (if it won't cause issues for the NWB export functions).  Options 2 and 3 would add complexity to the table/schema architecture.  Which option are you leaning towards?

**Comment by CBroz1** [comment]
My initial intuition was to put them upstream (2), preferring unused empty tables to those less-transparently-defined in the workflow, but I can see how empty tables could be confusing. If we don't have a good way for conditional activation upstream, then yes, let's move forward with the status quo (1). I think this should be paired with a section in each element's README listing suggested 'upstream workflow tables' (unless there's a better name for these cases?)

**Comment by kabilar** [comment]
I am not sure of a way to conditionally activate upstream tables.   I agree that we should add more documentation to the READMEs regarding the upstream workflow tables.

**Comment by CBroz1** [comment]
Submitted as documentation issues for established elements. Future elements can follow these models.
