### ISSUE TITLE
`make` methods within `element` modules are duplicated

### ISSUE THREAD

**Issue by kabilar** [datajoint/datajoint-elements#40]
### Problem
- `element-array-ephys` has several modules (e.g. `ephys`, `ephys-chronic`, `ephys-no-curation`) with slightly different table designs but the `make` methods are the same for each module.  Each time the `make` method changes in one module it must be copied over to the other modules.
- This is also the case for other `elements` (e.g. `element-calcium-imaging`).

### Requirement
- We need to implement a strategy so that we do not have to copy code between the modules whenever the contents of a `make` method changes.

### Solutions
- One possible solution is to move the contents of each `make` to a function and call that function from within the `make` method.

Tagging so that everyone is aware of the strategy that is decided.
@dimitri-yatsenko @iamamutt @CBroz1 @davidgodinez @GeetikaSi

**Comment by iamamutt** [comment]
Just a thought, but if you need to allow for some slight variations in each of the similar make functions, maybe a decorator?

```python
from functools import wraps

import datajoint as dj

dj.config["database.user"] = "root"
dj.config["database.password"] = "simple"

schema = dj.Schema("test")


def pre_make(make_fn):
    @wraps(make_fn)
    def make(self, key):
        print("1. Doing some initial things...")
        print(key)
        self.insert1(key)
        return make_fn(self, key)

    return make


@schema
class A(dj.Lookup):
    definition = """
    some_key    : varchar(8)
    """
    contents = [["hi"], ["wrld"]]


@schema
class B(dj.Computed):
    definition = """
    -> A
    """

    @pre_make
    def make(self, key):
        print("2. Doing more stuff...")
        print(self & key)


A()
B.populate()
```

Output:

```
Connecting root@localhost:3306
1. Doing some initial things...
{'some_key': 'hi'}
2. Doing more stuff...
*some_key   
+----------+
hi          
 (Total: 1)

1. Doing some initial things...
{'some_key': 'wrld'}
2. Doing more stuff...
*some_key   
+----------+
wrld        
 (Total: 1)
```

**Comment by dimitri-yatsenko** [comment]
In general, the purpose of the Elements is largely didactic: we need to show good simple motifs for scientists to use as starting examples. Therefore, code simplicity should be prioritized over code reuse. Factoring common functionality out into a separate function can simplify the design.  However, the use decorators will immediately put the code out of reach of a large slice of the coder population.

**Comment by CBroz1** [comment]
Sounds to me like competing goals of maintainability versus transparency; pushing edits to 1 or 3 places vs. didactic clarity. Could we keep a single `make` function elsewhere in the element? As a 'helper' function within the main schema (e.g., `ephys.py`) and then parallel schemas (e.g., `ephys_chronic.py`) import from there?

The decision here might be biased by a longterm goal to have a centralized 'merchant' or 'registry' of importable `make` functions.

**Comment by ttngu207** [comment]
Agreed with Dimitri here, using decorator may introduce a complexity level that is beyond (or discouraging) users. 
We certainly need to improve code reuse a bit here (too much code duplication in the different "flavors" of the element module). 
I think a strategy here is to refactor sections of the code where it makes sense, but still maintain/prioritize code readability.

**Comment by CBroz1** [comment]
Closing due to fulfillment of related internal [dev request](https://github.com/datajoint-company/science-team/issues/10)
