### ISSUE TITLE
Coloring scheme and layout of `elements.datajoint.org` does not match `docs.datajoint.org`

### ISSUE THREAD

**Issue by kabilar** [datajoint/datajoint-elements#41]

**Comment by CBroz1** [comment]
Our latest brand guide uses the following color schemes
1. Black and white
2. Light blue on white: #3293F1
3. Blue to purple gradient: #1CA9F9, #3B85F0, #685CEC*. Transition point takes place 2/3 of the way through the space.

* The brand guide lists another hex value for this purple that is wrong. This hex code was generated with reverse image lookup.

**Comment by kabilar** [comment]
Addressed with new mkdocs deployment strategy.
