### ISSUE TITLE
Clean top-level workflow directory for didactic clarity

### ISSUE THREAD

**Issue by CBroz1** [datajoint/datajoint-elements#44]
Currently, the workflows do double duty:
1. Integration tests and dev environments for the elements themselves
2. Didactic tools for the elements

As it stands the top-level directory of [workflow-array-ephys](https://github.com/datajoint/workflow-array-ephys) priorizes the (1) accessibility of dev tools at the expense of (2) new-user clarity. By moving docker and StandardConfig items to a subdirectory, I think we would make the workflow much more accessible for new users. We, as developers, will become accustomed to tools no matter where they are. New users might be overwhelmed not knowing which files they're meant to use versus ignore.

**Comment by kabilar** [comment]
Thanks @CBroz1  That is a good point.  I am looking into best practices and examples on how to organize these files.

**Comment by CBroz1** [comment]
This has been partially addressed by the creation of `docker` subdirectories. We could leave as is or go further by embedding both the `docker` directory and `requirements_test.txt` within tests.

**Comment by kabilar** [comment]
Thanks @CBroz1.  I would suggest that we keep the `docker` subdirectory at the top level.  Not sure about the `requirements_test.txt`.
