### ISSUE TITLE
Add links in `publications.md`

### ISSUE THREAD

**Issue by kabilar** [datajoint/datajoint-elements#47]
- Update [datajoint-citations/citations_used.md](https://github.com/datajoint/datajoint-citations/blob/master/citations_used.md) and then copy to [datajoint-elements/publications.md](https://github.com/datajoint/datajoint-elements/blob/main/publications.md).
- Add DOIs
- Update citations so that they refer to the journal (when possible) instead of BioRxiv.
- Rendering of markdown italics occurs correctly on GitHub but not on website.
- Add line breaks (`<br />`) as is [here](https://raw.githubusercontent.com/kabilar/datajoint-elements/publications/publications.md).
- Update list to be chronological

**Comment by CBroz1** [comment]
citations_used.md is generated automatically from the [citations_used.bib](https://github.com/datajoint/datajoint-citations/blob/master/citations_used.bib). The URLs should be added to the latter.

**Comment by kabilar** [comment]
Fix markdown rendering of italics, bold
