### ISSUE TITLE
Across repos, which should be templates?

### ISSUE THREAD

**Issue by CBroz1** [datajoint/datajoint-elements#76]
Currently, [workflow-calcium-imaging](https://github.com/datajoint/workflow-calcium-imaging) is a [public template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository). Neither [workflow-array-ephys](https://github.com/datajoint/workflow-array-ephys/) nor [element-array-ephys](https://github.com/datajoint/element-array-ephys/) nor [element-calcium-imaging](https://github.com/datajoint/element-calcium-imaging/) are templates. 

Which should be? Should we have documentation to show users how to use the template to structure their own workflow repo?

**Comment by kabilar** [comment]
> Which should be?

How about we set the `workflows` as templates but not the `elements`?  If you agree, please submit a ticket to the engineering team on the `science-team` repository.

> Should we have documentation to show users how to use the template to structure their own workflow repo?

Perhaps we can have a short description about GitHub templates for DataJoint workflows and a link to the [GitHub documentation](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template).

**Comment by kabilar** [comment]
All workflows are now `Templates`.
