### ISSUE TITLE
Links in the GitHub README do not work

### ISSUE THREAD

**Issue by kabilar** [datajoint/datajoint-elements#78]
- This repository is used to deploy the https://elements.datajoint.org site.  The links work correctly on https://elements.datajoint.org, but not on the GitHub repository.
- Links:
    - `Project Structure` section
        - `Management and Policies`
        - `Design Principles`
        - `Guidelines for Adoption`
        - `Glossary`
    - Tables under the heading `Background, Features, and Status`.

**Comment by kabilar** [comment]
Links are also broken within the tables under the heading `Backgound, Features, and Status`.

**Comment by CBroz1** [comment]
Closed via PR #81
